### ISSUE TITLE
Unknown locale Error

### ISSUE THREAD

**Issue by oini** [amishas157/wikidataLabelUpload#12]
On running `python script.py labels.bn.value bn`, I'm getting the following error even after doing a `git pull` and `pip install --upgrade git+https://github.com/wikimedia/pywikibot-core.git
`:

```
Traceback (most recent call last):
  File "script.py", line 2, in <module>
    import pywikibot
  File "/usr/local/lib/python2.7/site-packages/pywikibot/__init__.py", line 37, in <module>
    from pywikibot import config2 as config
  File "/usr/local/lib/python2.7/site-packages/pywikibot/config2.py", line 1101, in <module>
    userinterface_lang = getdefaultlocale()[0]
  File "/usr/local/Cellar/python/2.7.10_2/Frameworks/Python.framework/Versions/2.7/lib/python2.7/locale.py", line 543, in getdefaultlocale
    return _parse_localename(localename)
  File "/usr/local/Cellar/python/2.7.10_2/Frameworks/Python.framework/Versions/2.7/lib/python2.7/locale.py", line 475, in _parse_localename
    raise ValueError, 'unknown locale: %s' % localename
ValueError: unknown locale: UTF-8
```

cc @planemad @amishas157

**Comment by oini** [comment]
Fixed!
Thanks to @amishas15, fixed my `locale` by adding
```
export LC_ALL=en_US.UTF-8
export LANG=en_US.UTF-8
```
to my bash_profile
