### ISSUE TITLE
Skip over invalid Qids

### ISSUE THREAD

**Issue by planemad** [amishas157/wikidataLabelUpload#9]
Script crashes when encountering an invalid `qid`

```
Traceback (most recent call last):
  File "script.py", line 19, in <module>
    item = pywikibot.ItemPage(repo, l['id'])
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/pywikibot/page.py", line 3483, in __init__
    % self._link.title)
pywikibot.exceptions.InvalidTitle: 'Id' is not a valid item page title
<class 'pywikibot.exceptions.InvalidTitle'>
CRITICAL: Waiting for 1 network thread(s) to finish. Press ctrl-c to abort
```

**Comment by planemad** [comment]
Done
